version: '3'
services:
  evolution-api:
    container_name: evolution_api_supabase
    image: atendai/evolution-api
    restart: always
    ports:
      - "8081:8080"
    network_mode: "host"
    environment:
      # Autenticação
      - AUTHENTICATION_API_KEY=whatsapp-crm-evolution-key-2024-secure
      
      # Servidor
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8081
      
      # Database - Configurado mas não usado
      - DATABASE_ENABLED=false
      - DATABASE_PROVIDER=postgresql
      
      # Cache
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      
      # Logs
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      
      # CORS
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      
      # Configurações de instância
      - DEL_INSTANCE=false
      - INSTANCE_CLEANUP_INTERVAL=7200
      - INSTANCE_CLEANUP_DAYS=7
      
      # Webhook
      - WEBHOOK_BY_EVENTS=false
      
      # Dados a salvar
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
      
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

volumes:
  evolution_store:
  evolution_instances:
