version: '3'
services:
  evolution-api:
    container_name: evolution_api_official
    image: atendai/evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=whatsapp-crm-evolution-key-2024-secure
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      - DATABASE_ENABLED=false
      - DATABASE_PROVIDER=
      - DEL_INSTANCE=false
      - WEBHOOK_BY_EVENTS=false
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

volumes:
  evolution_store:
  evolution_instances:
